kind: Service
apiVersion: v1
metadata:
  name: sosmed-service
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: sosmed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosmed
  namespace: production
spec:
  selector:
    matchLabels:
      app: sosmed
  replicas: 1
  template:
    metadata:
      labels:
        app: sosmed
    spec:
      containers:
      - name: php-pesbuk
        image: irpank/pesbuk-app:tag
        ports:
          - containerPort: 80
        env:
        - name: DB_HOST
          value: "database-app.ch1pzpidls28.ap-northeast-2.rds.amazonaws.com"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: p-secret-fb
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: p-secret-fb
              key: DB_PASS
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: p-secret-fb
              key: DB_NAME
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sosmed-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: pesbukbp.komarudins.online
    http:
      paths:
      #- path: /
      - backend:
          serviceName: sosmed-service
          servicePort: 80
